colorscheme elflord
syntax on
set hidden
set tabstop=8 softtabstop=4 expandtab shiftwidth=4 smarttab
set smartindent
set nocp
set backspace=indent,eol,start

" Block cursor in command mode.
let &t_ti.="\e[1 q"
let &t_SI.="\e[5 q"
let &t_EI.="\e[1 q"
let &t_te.="\e[0 q"
highlight Cursor guifg=white guibg=black
highlight iCursor guifg=white guibg=steelblue
set guicursor=n-v-c:block-Cursor
set guicursor+=i:ver100-iCursor
set guicursor+=n-v-c:blinkon0
set guicursor+=i:blinkwait10
